version: "3.9"
services:
  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs/:/etc/ssl/certs/:ro
    depends_on:
      - backend

  backend:
    build:
      context: .
    container_name: backend
